services:
  bot:
    image: ghcr.io/disgoorg/vrcbot-template
    restart: unless-stopped
    volumes:
      - ./config.toml:/var/lib/config.toml
    command: -config=/var/lib/config.toml --sync-commands=true
    networks:
      - bot

networks:
  bot:
    name: vrcbot